name = "Balancing Overhaul"
author = "Grodus"
version = "3.2.8.1"
description = "Rebalances many general aspects of the game."
dst_compatible = true
all_clients_require_mod = true
client_only_mod = false
icon_atlas = "modicon.xml"
icon = "modicon.tex"
api_version = 10
api_version_dst = 10

server_filter_tags = {"tweak", "utility"}

-- Mod Configuration data
configuration_options =
{
	------------------------------
	--[[ Items ]]
	------------------------------
	{
		name = "Items",
		label = "Items", 
		options = {{description = "", data = 0}},
		default = 0,
	},
	{
		name = "frestoverheatrate",
		label = "Summer Frest Overheat Damage",
		options = {
			{description = "+1000%", data = 0.1},
			{description = "+400%", data = 0.25},
			{description = "+100%", data = 0.5},
			{description = "+67%", data = 0.6},
			{description = "+33%", data = 0.75},
			{description = "Unchanged", data = 1, hover = "Vanilla Setting"},
			{description = "-20%", data = 1.25},
			{description = "-33%", data = 1.5},
			{description = "-50%", data = 2, hover = "Recommended Setting"},
			{description = "-67%", data = 3},
			{description = "-75%", data = 4},
			{description = "-90%", data = 10},
		},
		default = 2,
	},
	{
		name = "scalemaildurability",
		label = "Scalemail Durability",
		options = {
			{description = "600", data = 600},
			{description = "800", data = 800},
			{description = "945", data = 945, hover = "Vanilla Setting"},
			{description = "1200", data = 1200},
			{description = "1400", data = 1400},
			{description = "1600", data = 1600},
			{description = "1800", data = 1800, hover = "Recommended Setting"},
			{description = "2000", data = 2000},
			{description = "2400", data = 2400},
			{description = "2800", data = 2800},
			{description = "3200", data = 3200},
			{description = "3600", data = 3600},
			{description = "4000", data = 4000},
		},
		default = 1800,
	},
	{
		name = "scalemailabsorption",
		label = "Scalemail Absorption",
		options = {
			{description = "50%", data = 0.5},
			{description = "55%", data = 0.55},
			{description = "60%", data = 0.6},
			{description = "65%", data = 0.65},
			{description = "70%", data = 0.7, hover = "Vanilla Setting"},
			{description = "75%", data = 0.75},
			{description = "80%", data = 0.8},
			{description = "85%", data = 0.85, hover = "Recommended Setting"},
			{description = "88%", data = 0.88},
			{description = "90%", data = 0.9},
			{description = "92%", data = 0.92},
			{description = "94%", data = 0.94},
			{description = "96%", data = 0.96},
			{description = "98%", data = 0.98},
			{description = "100%", data = 1},
		},
		default = 0.85,
	},
	{
		name = "snurtleshelldurability",
		label = "Snurtle Shell Durability",
		options = {
			{description = "250", data = 250},
			{description = "500", data = 500},
			{description = "735", data = 735, hover = "Vanilla Setting"},
			{description = "900", data = 900},
			{description = "1200", data = 1200},
			{description = "1500", data = 1500, hover = "Recommended Setting"},
			{description = "1800", data = 1800},
			{description = "2000", data = 2000},
			{description = "2400", data = 2400},
			{description = "2800", data = 2800},
			{description = "3200", data = 3200},
			{description = "3600", data = 3600},
			{description = "4000", data = 4000},
		},
		default = 1500,
	},
	{
		name = "snurtleshellcolumns",
		label = "Snurtle Shell # Columns",
		options = {
			{description = "0", data = 0, hover = "Vanilla Setting"},
			{description = "1", data = 1},
			{description = "2", data = 2, hover = "Recommended Setting"},
			{description = "3", data = 3},
			{description = "4", data = 4},
			{description = "5", data = 5},
			{description = "6", data = 6},
			{description = "7", data = 7},
			{description = "8", data = 8},
			{description = "9", data = 9},
			{description = "10", data = 10},
		},
		default = 2,
	},
	{
		name = "snurtleshellrows",
		label = "Snurtle Shell # Rows",
		options = {
			{description = "0", data = 0, hover = "Vanilla Setting"},
			{description = "1", data = 1},
			{description = "2", data = 2, hover = "Recommended Setting"},
			{description = "3", data = 3},
			{description = "4", data = 4},
			{description = "5", data = 5},
			{description = "6", data = 6},
			{description = "7", data = 7},
			{description = "8", data = 8},
			{description = "9", data = 9},
			{description = "10", data = 10},
		},
		default = 2,
	},
	{
		name = "beehatabsorption",
		label = "Bee Hat Absorption",
		options = {
			{description = "50%", data = 0.5},
			{description = "55%", data = 0.55},
			{description = "60%", data = 0.6},
			{description = "65%", data = 0.65},
			{description = "70%", data = 0.7},
			{description = "75%", data = 0.75},
			{description = "80%", data = 0.8, hover = "Vanilla Setting"},
			{description = "85%", data = 0.85},
			{description = "88%", data = 0.88},
			{description = "90%", data = 0.9},
			{description = "92%", data = 0.92},
			{description = "94%", data = 0.94},
			{description = "96%", data = 0.96},
			{description = "98%", data = 0.98},
			{description = "100%", data = 1},
		},
		default = 0.8,
	},
	{
		name = "orangeamuletdurability",
		label = "Lazy Forager Durability",
		options = {
			{description = "100", data = 100},
			{description = "200", data = 200},
			{description = "225", data = 225, hover = "Vanilla Setting"},
			{description = "300", data = 300},
			{description = "400", data = 400},
			{description = "500", data = 500},
			{description = "600", data = 600},
			{description = "700", data = 700},
			{description = "800", data = 800},
			{description = "900", data = 900},
			{description = "1000", data = 1000},
			{description = "1100", data = 1100},
			{description = "1200", data = 1200, hover = "Recommended Setting"},
			{description = "1400", data = 1400},
			{description = "1600", data = 1600},
			{description = "1800", data = 1800},
			{description = "2000", data = 2000},
			{description = "2400", data = 2400},
			{description = "2800", data = 2800},
			{description = "3200", data = 3200},
			{description = "3600", data = 3600},
			{description = "4000", data = 4000},
			{description = "5000", data = 5000},
			{description = "6000", data = 6000},
			{description = "7000", data = 7000},
			{description = "8000", data = 8000},
			{description = "9000", data = 9000},
			{description = "10000", data = 10000},
			{description = "20000", data = 20000},
			{description = "40000", data = 40000},
		},
		default = 1200,
	},
	{
		name = "orangeamuletrange",
		label = "Lazy Forager Range",
		options = {
			{description = "1", data = 1},
			{description = "2", data = 2},
			{description = "3", data = 3},
			{description = "4", data = 4, hover = "Vanilla Setting"},
			{description = "5", data = 5},
			{description = "6", data = 6},
			{description = "7", data = 7},
			{description = "8", data = 8},
			{description = "9", data = 9},
			{description = "10", data = 10},
			{description = "11", data = 11},
			{description = "12", data = 12, hover = "Recommended Setting"},
			{description = "13", data = 13},
			{description = "14", data = 14},
			{description = "15", data = 15},
			{description = "16", data = 16},
			{description = "17", data = 17},
			{description = "18", data = 18},
			{description = "19", data = 19},
			{description = "20", data = 20},
			{description = "24", data = 24},
			{description = "28", data = 28},
			{description = "32", data = 32},
			{description = "36", data = 36},
			{description = "40", data = 40},
			{description = "50", data = 50},
			{description = "60", data = 60},
			{description = "70", data = 70},
			{description = "80", data = 80},
			{description = "100", data = 100},
		},
		default = 12,
	},
	{
		name = "orangeamuleticd",
		label = "Lazy Forager ICD",
		options = {
			{description = "1 item/10 seconds", data = 10},
			{description = "1 item/5 seconds", data = 5},
			{description = "1 item/2 seconds", data = 2},
			{description = "1 item/second", data = 1},
			{description = "2 items/second", data = 0.5},
			{description = "3 items/second", data = 0.33, hover = "Vanilla Setting"},
			{description = "4 items/second", data = 0.25},
			{description = "5 items/second", data = 0.2},
			{description = "6 items/second", data = 0.15},
			{description = "8 items/second", data = 0.125, hover = "Recommended Setting"},
			{description = "10 items/second", data = 0.1},
			{description = "20 items/second", data = 0.05},
			{description = "40 items/second", data = 0.025},
			{description = "80 items/second", data = 0.0125},
		},
		default = 0.125,
	},
	------------------------------
	--[[ Waterproofness ]]
	------------------------------
	{
		name = "Waterproofness",
		label = "Waterproofness", 
		options = {{description = "", data = 0}},
		default = 0,
	},
	{
		name = "waterproofness",
		label = "Waterballoon wetness duration",
		options = {
			{description = "50 Seconds", data = 50},
			{description = "45 Seconds", data = 45},
			{description = "40 Seconds", data = 40},
			{description = "35 Seconds", data = 35},
			{description = "30 Seconds", data = 30, hover = "Recommended Setting"},
			{description = "25 Seconds", data = 25},
			{description = "20 Seconds", data = 20},
			{description = "15 Seconds", data = 15},
			{description = "10 Seconds", data = 10},
			{description = "5 Seconds", data = 5},
			{description = "0 Seconds", data = 0, hover = "Vanilla Setting"},
		},
		default = 30,
	},
	{
		name = "umbrellaproof",
		label = "Umbrella Waterproofness",
		options = {
			{description = "60%", data = 0.6},
			{description = "65%", data = 0.65},
			{description = "70%", data = 0.7, hover = "Recommended Setting"},
			{description = "75%", data = 0.75},
			{description = "80%", data = 0.8},
			{description = "85%", data = 0.85, hover = "Vanilla Setting"},
			{description = "90%", data = 0.9},
			{description = "95%", data = 0.95},
			{description = "100%", data = 1},
		},
		default = 0.7,
	},
	{
		name = "rainhatproof",
		label = "Rain Hat Waterproofness",
		options = {
			{description = "50%", data = 0.5},
			{description = "55%", data = 0.55},
			{description = "60%", data = 0.6},
			{description = "65%", data = 0.65},
			{description = "70%", data = 0.7, hover = "Vanilla Setting"},
			{description = "75%", data = 0.75},
			{description = "80%", data = 0.8},
			{description = "85%", data = 0.85, hover = "Recommended Setting"},
			{description = "90%", data = 0.9},
			{description = "95%", data = 0.95},
			{description = "100%", data = 1},
		},
		default = 0.85,
	},
	{
		name = "cookiehatproof",
		label = "Cookie Hat Waterproofness",
		options = {
			{description = "10%", data = 0.1},
			{description = "15%", data = 0.15},
			{description = "20%", data = 0.2},
			{description = "25%", data = 0.25},
			{description = "30%", data = 0.3},
			{description = "35%", data = 0.35, hover = "Vanilla Setting"},
			{description = "40%", data = 0.4},
			{description = "45%", data = 0.45},
			{description = "50%", data = 0.5, hover = "Recommended Setting"},
			{description = "55%", data = 0.55},
			{description = "60%", data = 0.6},
			{description = "65%", data = 0.65},
			{description = "70%", data = 0.7},
			{description = "75%", data = 0.75},
			{description = "80%", data = 0.8},
			{description = "85%", data = 0.85},
			{description = "90%", data = 0.9},
			{description = "95%", data = 0.95},
			{description = "100%", data = 1},
		},
		default = 0.5,
	},
	------------------------------
	--[[ Structures ]]
	------------------------------
	{
		name = "Structures",
		label = "Structures", 
		options = {{description = "", data = 0}},
		default = 0,
	},
	{
		name = "potfernsanity",
		label = "Potted Fern Sanity Aura",
		options = {
			{description = "+0 per minute", data = 0, hover = "Vanilla Setting"},
			{description = "+0.33 per minute", data = 0.33},
			{description = "+0.67 per minute", data = 0.67},
			{description = "+1 per minute", data = 1},
			{description = "+1.33 per minute", data = 1.33},
			{description = "+1.67 per minute", data = 1.67, hover = "Recommended Setting"},
			{description = "+2 per minute", data = 2},
			{description = "+2.33 per minute", data = 2.33},
			{description = "+2.67 per minute", data = 2.67},
			{description = "+3 per minute", data = 3},
			{description = "+3.33 per minute", data = 3.33},
			{description = "+3.67 per minute", data = 3.67},
			{description = "+4 per minute", data = 4},
			{description = "+4.33 per minute", data = 4.33},
			{description = "+4.67 per minute", data = 4.67},
			{description = "+5 per minute", data = 5},
			{description = "+6 per minute", data = 6},
			{description = "+7 per minute", data = 7},
			{description = "+8 per minute", data = 8},
			{description = "+9 per minute", data = 9},
			{description = "+10 per minute", data = 10},
		},
		default = 1.67,
	},
	{
		name = "potsuccsanity",
		label = "Potted Succulent Sanity Aura",
		options = {
			{description = "+0 per minute", data = 0, hover = "Vanilla Setting"},
			{description = "+0.33 per minute", data = 0.33},
			{description = "+0.67 per minute", data = 0.67},
			{description = "+1 per minute", data = 1},
			{description = "+1.33 per minute", data = 1.33},
			{description = "+1.67 per minute", data = 1.67},
			{description = "+2 per minute", data = 2},
			{description = "+2.33 per minute", data = 2.33},
			{description = "+2.67 per minute", data = 2.67},
			{description = "+3 per minute", data = 3},
			{description = "+3.33 per minute", data = 3.33, hover = "Recommended Setting"},
			{description = "+3.67 per minute", data = 3.67},
			{description = "+4 per minute", data = 4},
			{description = "+4.33 per minute", data = 4.33},
			{description = "+4.67 per minute", data = 4.67},
			{description = "+5 per minute", data = 5},
			{description = "+6 per minute", data = 6},
			{description = "+7 per minute", data = 7},
			{description = "+8 per minute", data = 8},
			{description = "+9 per minute", data = 9},
			{description = "+10 per minute", data = 10},
		},
		default = 3.33,
	},
	{
		name = "dragonflychestcolumns",
		label = "Scaled Chest # Columns",
		options = {
			{description = "Dont Change", data = 0, hover = "Vanilla Setting"},
			{description = "1", data = 1},
			{description = "2", data = 2},
			{description = "3", data = 3},
			{description = "4", data = 4, hover = "Recommended Setting"},
			{description = "5", data = 5},
			{description = "6", data = 6},
			{description = "7", data = 7},
			{description = "8", data = 8},
			{description = "9", data = 9},
			{description = "10", data = 10},
		},
		default = 4,
	},
	{
		name = "dragonflychestrows",
		label = "Scaled Chest # Rows",
		options = {
			{description = "Dont Change", data = 0, hover = "Vanilla Setting"},
			{description = "1", data = 1},
			{description = "2", data = 2},
			{description = "3", data = 3},
			{description = "4", data = 4, hover = "Recommended Setting"},
			{description = "5", data = 5},
			{description = "6", data = 6},
			{description = "7", data = 7},
			{description = "8", data = 8},
			{description = "9", data = 9},
			{description = "10", data = 10},
		},
		default = 4,
	},
	{
		name = "minotaurchestcolumns",
		label = "Ornate Chest # Columns",
		options = {
			{description = "Dont Change", data = 0, hover = "Vanilla Setting"},
			{description = "1", data = 1},
			{description = "2", data = 2},
			{description = "3", data = 3},
			{description = "4", data = 4},
			{description = "5", data = 5, hover = "Recommended Setting"},
			{description = "6", data = 6},
			{description = "7", data = 7},
			{description = "8", data = 8},
			{description = "9", data = 9},
			{description = "10", data = 10},
		},
		default = 5,
	},
	{
		name = "minotaurchestrows",
		label = "Ornate Chest # Rows",
		options = {
			{description = "Dont Change", data = 0, hover = "Vanilla Setting"},
			{description = "1", data = 1},
			{description = "2", data = 2},
			{description = "3", data = 3},
			{description = "4", data = 4},
			{description = "5", data = 5, hover = "Recommended Setting"},
			{description = "6", data = 6},
			{description = "7", data = 7},
			{description = "8", data = 8},
			{description = "9", data = 9},
			{description = "10", data = 10},
		},
		default = 5,
	},
	------------------------------
	--[[ Characters ]]
	------------------------------
	{
		name = "Characters",
		label = "Characters", 
		options = {{description = "", data = 0}},
		default = 0,
	},
	{
		name = "wortoxheal",
		label = "Wortox Soul Heal Loss Per Player",
		options = {
			{description = "15 HP", data = 15},
			{description = "14 HP", data = 14},
			{description = "13 HP", data = 13},
			{description = "12 HP", data = 12},
			{description = "11 HP", data = 11},
			{description = "10 HP", data = 10},
			{description = "9 HP", data = 9},
			{description = "8 HP", data = 8},
			{description = "7 HP", data = 7},
			{description = "6 HP", data = 6},
			{description = "5 HP", data = 5},
			{description = "4 HP", data = 4},
			{description = "3 HP", data = 3, hover = "Recommended Setting"},
			{description = "2 HP", data = 2},
			{description = "1 HP", data = 1},
			{description = "0 HP", data = 0},
		},
		default = 3,
	},
	{
		name = "wortoxsouls",
		label = "Number Souls Wortox Can Hold",
		options = {
			{description = "50", data = 50},
			{description = "40", data = 40},
			{description = "35", data = 35},
			{description = "30", data = 30, hover = "Recommended Setting"},
			{description = "25", data = 25},
			{description = "20", data = 20, hover = "Vanilla Setting"},
			{description = "18", data = 18},
			{description = "16", data = 16},
			{description = "14", data = 14},
			{description = "12", data = 12},
			{description = "10", data = 10},
			{description = "8", data = 8},
			{description = "6", data = 6},
			{description = "4", data = 4},
			{description = "2", data = 2},
			{description = "0", data = 0},
		},
		default = 30,
	},
	{
		name = "willowdebuffrate",
		label = "Willow Fire Debuff Rate",
		options = {
			{description = "0", data = 0, hover = "Vanilla Setting"},
			{description = "0.025", data = 0.025},
			{description = "0.05", data = 0.05, hover = "Recommended Setting"},
			{description = "0.075", data = 0.075},
			{description = "0.1", data = 0.1},
			{description = "0.15", data = 0.15},
			{description = "0.2", data = 0.2},
			{description = "0.25", data = 0.25},
			{description = "0.3", data = 0.3},
			{description = "0.35", data = 0.35},
			{description = "0.4", data = 0.4},
			{description = "0.5", data = 0.5},
			{description = "0.75", data = 0.75},
			{description = "1", data = 1},
			{description = "2", data = 2},
			{description = "3", data = 3},
			{description = "4", data = 4},
		},
		default = 0.05,
	},
	{
		name = "willowfiremult",
		label = "Willow Fire Weapon Multiplier",
		options = {
			{description = "1x", data = 1, hover = "Vanilla Setting"},
			{description = "2x", data = 2, hover = "Recommended Setting"},
			{description = "3x", data = 3},
			{description = "4x", data = 4},
			{description = "5x", data = 5},
			{description = "10x", data = 10},
			{description = "20x", data = 20},
		},
		default = 2,
	},
	{
		name = "berniehealrate",
		label = "Bernie Healing Rate",
		options = {
			{description = "0", data = 0, hover = "Vanilla Setting"},
			{description = "1", data = 1, hover = "Recommended Setting"},
			{description = "2", data = 2},
			{description = "3", data = 3},
			{description = "4", data = 4},
			{description = "5", data = 5},
			{description = "6", data = 6},
			{description = "7", data = 7},
			{description = "8", data = 8},
			{description = "9", data = 9},
			{description = "10", data = 10},
			{description = "20", data = 20},
			{description = "50", data = 50},
			{description = "100", data = 100},
		},
		default = 1,
	},
	{
		name = "winonahealthincrease",
		label = "Winona Max Health Increase",
		options = {
			{description = "-25", data = -25},
			{description = "-20", data = -20},
			{description = "-15", data = -15},
			{description = "-10", data = -10},
			{description = "-5", data = -5},
			{description = "0", data = 0, hover = "Vanilla Setting"},
			{description = "5", data = 5},
			{description = "10", data = 10},
			{description = "15", data = 15},
			{description = "20", data = 20},
			{description = "25", data = 25, hover = "Recommended Setting"},
			{description = "30", data = 30},
			{description = "35", data = 35},
			{description = "40", data = 40},
			{description = "45", data = 45},
			{description = "50", data = 50},
		},
		default = 25,
	},
	{
		name = "winonahungerincrease",
		label = "Winona Max Hunger Increase",
		options = {
			{description = "-25", data = -25},
			{description = "-20", data = -20},
			{description = "-15", data = -15},
			{description = "-10", data = -10},
			{description = "-5", data = -5},
			{description = "0", data = 0, hover = "Vanilla Setting"},
			{description = "5", data = 5},
			{description = "10", data = 10},
			{description = "15", data = 15},
			{description = "20", data = 20},
			{description = "25", data = 25, hover = "Recommended Setting"},
			{description = "30", data = 30},
			{description = "35", data = 35},
			{description = "40", data = 40},
			{description = "45", data = 45},
			{description = "50", data = 50},
		},
		default = 25,
	},
	{
		name = "winonasanityresistgrue",
		label = "Winona Sanity Change Grue",
		options = {
			{description = "-25", data = -25},
			{description = "-20", data = -20},
			{description = "-15", data = -15},
			{description = "-10", data = -10},
			{description = "-5", data = -5},
			{description = "0", data = 0, hover = "Vanilla Setting"},
			{description = "5", data = 5},
			{description = "10", data = 10},
			{description = "15", data = 15, hover = "Recommended Setting"},
			{description = "20", data = 20},
			{description = "25", data = 25},
			{description = "30", data = 30},
			{description = "35", data = 35},
			{description = "40", data = 40},
			{description = "45", data = 45},
			{description = "50", data = 50},
		},
		default = 15,
	},
	{
		name = "winonasanitybuildstructure",
		label = "Winona Sanity Build Structure",
		options = {
			{description = "-25", data = -25},
			{description = "-20", data = -20},
			{description = "-15", data = -15},
			{description = "-10", data = -10},
			{description = "-5", data = -5},
			{description = "0", data = 0, hover = "Vanilla Setting"},
			{description = "5", data = 5},
			{description = "10", data = 10, hover = "Recommended Setting"},
			{description = "15", data = 15},
			{description = "20", data = 20},
			{description = "25", data = 25},
			{description = "30", data = 30},
			{description = "35", data = 35},
			{description = "40", data = 40},
			{description = "45", data = 45},
			{description = "50", data = 50},
		},
		default = 10,
	},
	{
		name = "winonabonusdurability",
		label = "Winona Item Durability Bonus",
		options = {
			{description = "+0%", data = 1, hover = "Vanilla Setting"},
			{description = "+5%", data = 1.05},
			{description = "+10%", data = 1.1, hover = "Recommended Setting"},
			{description = "+15%", data = 1.15},
			{description = "+20%", data = 1.2},
			{description = "+25%", data = 1.25},
			{description = "+30%", data = 1.3},
			{description = "+35%", data = 1.35},
			{description = "+40%", data = 1.4},
			{description = "+50%", data = 1.5},
			{description = "+75%", data = 1.75},
			{description = "+100%", data = 2},
			{description = "+200%", data = 3},
			{description = "+300%", data = 4},
		},
		default = 1.1,
	},
	{
		name = "winonahungerdrain",
		label = "Winona Hunger Drain",
		options = {
			{description = "-50%", data = 0.5},
			{description = "-20%", data = 0.8},
			{description = "-15%", data = 0.85},
			{description = "-10%", data = 0.9},
			{description = "-5%", data = 0.95},
			{description = "+0%", data = 1, hover = "Vanilla Setting"},
			{description = "+5%", data = 1.05},
			{description = "+10%", data = 1.1},
			{description = "+15%", data = 1.15},
			{description = "+20%", data = 1.2, hover = "Recommended Setting"},
			{description = "+25%", data = 1.25},
			{description = "+30%", data = 1.3},
			{description = "+35%", data = 1.35},
			{description = "+40%", data = 1.4},
			{description = "+50%", data = 1.5},
			{description = "+75%", data = 1.75},
			{description = "+100%", data = 2},
			{description = "+200%", data = 3},
			{description = "+300%", data = 4},
		},
		default = 1.2,
	},
	------------------------------
	--[[ Mobs ]]
	------------------------------
	{
		name = "Mobs",
		label = "Mobs", 
		options = {{description = "", data = 0}},
		default = 0,
	},
	{
		name = "rockyhealth",
		label = "Rock Lobster Health",
		options = {
			{description = "100", data = 100},
			{description = "200", data = 200},
			{description = "300", data = 300},
			{description = "400", data = 400},
			{description = "500", data = 500},
			{description = "600", data = 600},
			{description = "800", data = 800},
			{description = "1200", data = 1200},
			{description = "1800", data = 1800, hover = "Recommended Setting"},
			{description = "2400", data = 2400},
			{description = "3000", data = 3000, hover = "Vanilla Setting"},
			{description = "3600", data = 3600},
			{description = "4000", data = 4000},
			{description = "5000", data = 5000},
			{description = "6000", data = 6000},
			{description = "7000", data = 7000},
			{description = "8000", data = 8000},
			{description = "9000", data = 9000},
			{description = "10000", data = 10000},
		},
		default = 1800,
	},
	{
		name = "rockyabsorption",
		label = "Rock Lobster Absorption",
		options = {
			{description = "50%", data = 0.5},
			{description = "55%", data = 0.55},
			{description = "60%", data = 0.6},
			{description = "65%", data = 0.65},
			{description = "70%", data = 0.7},
			{description = "75%", data = 0.75},
			{description = "80%", data = 0.8, hover = "Recommended Setting"},
			{description = "85%", data = 0.85},
			{description = "88%", data = 0.88},
			{description = "90%", data = 0.9},
			{description = "92%", data = 0.92},
			{description = "96%", data = 0.95, hover = "Vanilla Setting"},
			{description = "98%", data = 0.98},
			{description = "100%", data = 1},
		},
		default = 0.8,
	},
	{
		name = "beestingerdroprate",
		label = "Bee Stinger Droprate",
		options = {
			{description = "0%", data = 0},
			{description = "10%", data = 0.1},
			{description = "20%", data = 0.2},
			{description = "25%", data = 0.25, hover = "Recommended Setting"},
			{description = "30%", data = 0.3},
			{description = "40%", data = 0.4},
			{description = "50%", data = 0.5},
			{description = "55%", data = 0.55},
			{description = "60%", data = 0.6},
			{description = "65%", data = 0.65},
			{description = "70%", data = 0.7},
			{description = "75%", data = 0.75},
			{description = "80%", data = 0.8},
			{description = "83%", data = 0.83, hover = "Vanilla Setting"},
			{description = "85%", data = 0.85},
			{description = "88%", data = 0.88},
			{description = "90%", data = 0.9},
			{description = "95%", data = 0.95},
			{description = "100%", data = 1},
		},
		default = 0.25,
	},
	{
		name = "beehoneydroprate",
		label = "Bee Honey Droprate",
		options = {
			{description = "0%", data = 0},
			{description = "10%", data = 0.1},
			{description = "16%", data = 0.16, hover = "Vanilla Setting"},
			{description = "20%", data = 0.2},
			{description = "25%", data = 0.25, hover = "Recommended Setting"},
			{description = "30%", data = 0.3},
			{description = "40%", data = 0.4},
			{description = "50%", data = 0.5},
			{description = "55%", data = 0.55},
			{description = "60%", data = 0.6},
			{description = "65%", data = 0.65},
			{description = "70%", data = 0.7},
			{description = "75%", data = 0.75},
			{description = "80%", data = 0.8},
			{description = "85%", data = 0.85},
			{description = "88%", data = 0.88},
			{description = "90%", data = 0.9},
			{description = "95%", data = 0.95},
			{description = "100%", data = 1},
		},
		default = 0.25,
	},
	------------------------------
	--[[ Misc ]]
	------------------------------
	{
		name = "Misc",
		label = "Misc", 
		options = {{description = "", data = 0}},
		default = 0,
	},
	{
		name = "experimental",
		label = "Features in testing",
		options = {
			{description = "On", data = true, hover = "Recommended Setting"},
			{description = "Off", data = false},
		},
		default = true,
	},
	{
		name = "SpookChance",
		label = "Chance of bats spooking you",
		options = {
			{description = "100%", data = 1, hover = "Unplayable"},
			{description = "90%", data = 0.9},
			{description = "80%", data = 0.8},
			{description = "70%", data = 0.7},
			{description = "60%", data = 0.6},
			{description = "50%", data = 0.5},
			{description = "40%", data = 0.4},
			{description = "30%", data = 0.3},
			{description = "20%", data = 0.2},
			{description = "10%", data = 0.1},
			{description = "0%", data = 0, hover = "Recommended Setting"},
		},
		default = 0,
	},
	{
		name = "thulecitefill",
		label = "Thulecite Fragments Refill Durability",
		options = {
			{description = "0", data = 0, hover = "Vanilla Setting"},
			{description = "50", data = 50},
			{description = "100", data = 100},
			{description = "150", data = 150},
			{description = "200", data = 200, hover = "Recommended Setting"},
			{description = "250", data = 250},
			{description = "300", data = 300},
			{description = "350", data = 350},
			{description = "400", data = 400},
			{description = "450", data = 450},
			{description = "500", data = 500},
			{description = "550", data = 550},
			{description = "600", data = 600},
		},
		default = 200,
	},
	{
		name = "nightmarefill",
		label = "Nightmare Fuel Refill Durability",
		options = {
			{description = "0", data = 0, hover = "Vanilla Setting"},
			{description = "50", data = 50},
			{description = "100", data = 100},
			{description = "150", data = 150, hover = "Recommended Setting"},
			{description = "200", data = 200},
			{description = "250", data = 250},
			{description = "300", data = 300},
			{description = "350", data = 350},
			{description = "400", data = 400},
			{description = "450", data = 450},
			{description = "500", data = 500},
			{description = "550", data = 550},
			{description = "600", data = 600},
		},
		default = 150,
	},
	{
		name = "boneshardfill",
		label = "Bone Shard Refill Durability",
		options = {
			{description = "0", data = 0, hover = "Vanilla Setting"},
			{description = "5", data = 5},
			{description = "10", data = 10},
			{description = "25", data = 25, hover = "Recommended Setting"},
			{description = "40", data = 40},
			{description = "50", data = 50},
			{description = "75", data = 75},
			{description = "100", data = 100},
			{description = "125", data = 125},
			{description = "150", data = 150},
			{description = "175", data = 175},
			{description = "200", data = 200},
			{description = "250", data = 250},
			{description = "300", data = 300},
			{description = "350", data = 350},
			{description = "400", data = 400},
		},
		default = 25,
	},
	------------------------------
	--[[ Recipes ]]
	------------------------------
	{
		name = "Recipes",
		label = "Recipes", 
		options = {{description = "", data = 0}},
		default = 0,
	},
	{
		name = "DartAmount",
		label = "Amount of darts crafted",
		options = {
			{description = "1", data = 1, hover = "Vanilla Setting"},
			{description = "2", data = 2},
			{description = "3", data = 3},
			{description = "4", data = 4},
			{description = "5", data = 5},
			{description = "6", data = 6},
			{description = "7", data = 7},
			{description = "8", data = 8},
			{description = "9", data = 9},
			{description = "10", data = 10},
		},
		default = 2,
	},
	------------------------------
	--[[ Turfs ]]
	------------------------------
	{
		name = "Turfs",
		label = "Turfs", 
		options = {{description = "", data = 0}},
		default = 0,
	},
	{
		name = "woodturfspeed",
		label = "Wooden Flooring Speed Increase",
		options = {
			{description = "+0%", data = 1, hover = "Vanilla Setting"},
			{description = "+5%", data = 1.05},
			{description = "+10%", data = 1.1},
			{description = "+15%", data = 1.15},
			{description = "+20%", data = 1.2, hover = "Recommended Setting"},
			{description = "+25%", data = 1.25},
			{description = "+30%", data = 1.3},
			{description = "+35%", data = 1.35},
			{description = "+40%", data = 1.4},
		},
		default = 1.2,
	},
	{
		name = "carpetturfsanity",
		label = "Carpeted Flooring Sanity Aura",
		options = {
			{description = "+0 per minute", data = 0, hover = "Vanilla Setting"},
			{description = "+0.33 per minute", data = 0.33},
			{description = "+0.67 per minute", data = 0.67},
			{description = "+1 per minute", data = 1},
			{description = "+1.33 per minute", data = 1.33, hover = "Recommended Setting"},
			{description = "+1.67 per minute", data = 1.67},
			{description = "+2 per minute", data = 2},
			{description = "+3 per minute", data = 3},
			{description = "+4 per minute", data = 4},
			{description = "+5 per minute", data = 5},
		},
		default = 1.33,
	},
	{
		name = "carpetturfwaterproofness",
		label = "Carpeted Flooring Waterproofness",
		options = {
			{description = "0%", data = 1, hover = "Vanilla Setting"},
			{description = "10%", data = 0.9},
			{description = "20%", data = 0.8, hover = "Recommended Setting"},
			{description = "30%", data = 0.7},
			{description = "40%", data = 0.6},
			{description = "50%", data = 0.5},
			{description = "60%", data = 0.4},
			{description = "70%", data = 0.3},
			{description = "80%", data = 0.2},
			{description = "90%", data = 0.1},
			{description = "100%", data = 0},
		},
		default = 0.8,
	},
	{
		name = "checkeredturfsanity",
		label = "Checkered Flooring Sanity Aura",
		options = {
			{description = "+0 per minute", data = 0, hover = "Vanilla Setting"},
			{description = "+0.33 per minute", data = 0.33},
			{description = "+0.67 per minute", data = 0.67},
			{description = "+1 per minute", data = 1},
			{description = "+1.33 per minute", data = 1.33},
			{description = "+1.67 per minute", data = 1.67},
			{description = "+2 per minute", data = 2},
			{description = "+2.33 per minute", data = 2.33},
			{description = "+2.67 per minute", data = 2.67},
			{description = "+3 per minute", data = 3},
			{description = "+3.33 per minute", data = 3.33, hover = "Recommended Setting"},
			{description = "+3.67 per minute", data = 3.67},
			{description = "+4 per minute", data = 4},
			{description = "+5 per minute", data = 5},
			{description = "+6 per minute", data = 6},
			{description = "+8 per minute", data = 8},
			{description = "+10 per minute", data = 10},
			{description = "+15 per minute", data = 15},
			{description = "+20 per minute", data = 20},
		},
		default = 3.33,
	},
	{
		name = "scaledturfspeed",
		label = "Scaled Flooring Speed Increase",
		options = {
			{description = "+0%", data = 1, hover = "Vanilla Setting"},
			{description = "+5%", data = 1.05},
			{description = "+10%", data = 1.1, hover = "Recommended Setting"},
			{description = "+15%", data = 1.15},
			{description = "+20%", data = 1.2},
			{description = "+25%", data = 1.25},
			{description = "+30%", data = 1.3},
			{description = "+35%", data = 1.35},
			{description = "+40%", data = 1.4},
			{description = "+45%", data = 1.45},
			{description = "+50%", data = 1.5},
			{description = "+55%", data = 1.55},
			{description = "+60%", data = 1.6},
		},
		default = 1.1,
	},
	{
		name = "scaledturfwinterinsulation",
		label = "Scaled Flooring Winter Insulation",
		options = {
			{description = "0 Seconds", data = 0, hover = "Vanilla Setting"},
			{description = "40 Seconds", data = 40},
			{description = "80 Seconds", data = 80},
			{description = "120 Seconds", data = 120},
			{description = "160 Seconds", data = 160},
			{description = "200 Seconds", data = 200},
			{description = "240 Seconds", data = 240},
			{description = "280 Seconds", data = 280},
			{description = "320 Seconds", data = 320, hover = "Recommended Setting"},
			{description = "360 Seconds", data = 360},
			{description = "400 Seconds", data = 400},
		},
		default = 320,
	},
	{
		name = "scaledturfsmolder",
		label = "Scaled Flooring Smolder Resistance",
		options = {
			{description = "Resistant", data = false, hover = "Recommended Setting"},
			{description = "Not Resistant", data = true, hover = "Vanilla Setting"},
		},
		default = false,
	},
	{
		name = "scaledturfwildfire",
		label = "Scaled Flooring Wildfire Resistance",
		options = {
			{description = "Resistant", data = true, hover = "Recommended Setting"},
			{description = "Not Resistant", data = false, hover = "Vanilla Setting"},
		},
		default = true,
	},
	------------------------------
	--[[ Walls ]]
	------------------------------
	{
		name = "Walls",
		label = "Walls", 
		options = {{description = "", data = 0}},
		default = 0,
	},
	{
		name = "HealthHayWalls",
		label = "Hay Walls Health",
		options = {
			{description = "10", data = 10},
			{description = "20", data = 20},
			{description = "40", data = 40},
			{description = "60", data = 60},
			{description = "80", data = 80},
			{description = "100", data = 100, hover = "Vanilla Setting"},
			{description = "120", data = 120},
			{description = "160", data = 160},
			{description = "200", data = 200, hover = "Recommended Setting"},
			{description = "240", data = 240},
			{description = "280", data = 280},
			{description = "320", data = 320},
			{description = "360", data = 360},
			{description = "400", data = 400},
			{description = "500", data = 500},
			{description = "600", data = 600},
			{description = "800", data = 800},
			{description = "1000", data = 1000},
		},
		default = 200,
	},
	{
		name = "HealthWoodWalls",
		label = "Wood Walls Health",
		options = {
			{description = "20", data = 20},
			{description = "40", data = 40},
			{description = "80", data = 80},
			{description = "120", data = 120},
			{description = "160", data = 160},
			{description = "200", data = 200, hover = "Vanilla Setting"},
			{description = "260", data = 260},
			{description = "320", data = 320},
			{description = "380", data = 380},
			{description = "400", data = 400, hover = "Recommended Setting"},
			{description = "440", data = 440},
			{description = "500", data = 500},
			{description = "600", data = 600},
			{description = "800", data = 800},
			{description = "1000", data = 1000},
			{description = "1500", data = 1500},
			{description = "2000", data = 2000},
		},
		default = 400,
	},
	{
		name = "HealthStoneWalls",
		label = "Stone Walls Health",
		options = {
			{description = "40", data = 40},
			{description = "80", data = 80},
			{description = "160", data = 160},
			{description = "240", data = 240},
			{description = "320", data = 320},
			{description = "400", data = 400, hover = "Vanilla Setting"},
			{description = "520", data = 520},
			{description = "640", data = 640},
			{description = "760", data = 760},
			{description = "800", data = 800, hover = "Recommended Setting"},
			{description = "880", data = 880},
			{description = "1000", data = 1000},
			{description = "1200", data = 1200},
			{description = "1600", data = 1600},
			{description = "2000", data = 2000},
			{description = "3000", data = 3000},
			{description = "4000", data = 4000},
		},
		default = 800,
	},
	{
		name = "HealthRuinsWalls",
		label = "Thulecite Walls Health",
		options = {
			{description = "80", data = 80},
			{description = "160", data = 160},
			{description = "320", data = 320},
			{description = "480", data = 480},
			{description = "640", data = 640},
			{description = "800", data = 800, hover = "Vanilla Setting"},
			{description = "1040", data = 1040},
			{description = "1280", data = 1280},
			{description = "1520", data = 1520},
			{description = "1600", data = 1600, hover = "Recommended Setting"},
			{description = "1760", data = 1760},
			{description = "2000", data = 2000},
			{description = "2400", data = 2400},
			{description = "3200", data = 3200},
			{description = "4000", data = 4000},
			{description = "6000", data = 6000},
			{description = "8000", data = 8000},
		},
		default = 1600,
	},
	{
		name = "HealthMoonrockWalls",
		label = "Moonrock Walls Health",
		options = {
			{description = "100", data = 100},
			{description = "200", data = 200},
			{description = "300", data = 300},
			{description = "400", data = 400},
			{description = "500", data = 500},
			{description = "600", data = 600, hover = "Vanilla Setting"},
			{description = "700", data = 700},
			{description = "800", data = 800},
			{description = "900", data = 900},
			{description = "1000", data = 1000},
			{description = "1200", data = 1200, hover = "Recommended Setting"},
			{description = "1400", data = 1400},
			{description = "1600", data = 1600},
			{description = "1800", data = 1800},
			{description = "2000", data = 2000},
			{description = "2400", data = 2400},
			{description = "2800", data = 2800},
			{description = "3200", data = 3200},
			{description = "3600", data = 3600},
			{description = "4000", data = 4000},
			{description = "5000", data = 5000},
			{description = "6000", data = 6000},
		},
		default = 1200,
	},
}
